[package]
name = "pso2-modpatcher"
version = "0.1.0-alpha.0"
authors = ["Eidolon <furyhunter600@gmail.com>"]
edition = "2018"
publish = false

[dependencies]
ages-ice-archive = "0.3"
anyhow = "1"
ascii = "1"
structopt = "0.3"
